#define abs abs_
#define atoi atoi_
#define fabs fabs_
#define isalpha isalpha_
#define isdigit isdigit_
#define isspace isspace_
#define isupper isupper_
#define memmove memmove_
#define strrchr strrchr_
#define strcmp strcmp_
#define strdup strdup_
#define stricmp stricmp_
#define strlen strlen_
#define strncmp strncmp_
#define strncpy strncpy_
#define strnicmp strnicmp_
#define strstr strstr_
#define strtoul strtoul_
#define tolower tolower_
#define toupper toupper_