namespace System
{
    public enum ConsoleKey : byte
    {
        None = 0,
        Backspace = 8,
        Tab,
        Clear = 12,
        Enter = 13, Return = 13,
        Pause = 19,
        Capital = 20, CapsLock = 20,
        Escape = 27,
        Space = 32,
        Prior = 33, PageUp = 33,
        Next = 34, PageDown = 34,
        End,
        Home,
        Left,
        Up,
        Right,
        Down,
        Select,
        Print,
        Execute,
        Snapshot = 44, PrintScreen = 44,
        Insert,
        Delete,
        Help,
        D0,
        D1,
        D2,
        D3,
        D4,
        D5,
        D6,
        D7,
        D8,
        D9,
        A = 65,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        LeftWindows,
        RightWindows,
        Applications,
        Sleep = 95,
        NumPad0,
        NumPad1,
        NumPad2,
        NumPad3,
        NumPad4,
        NumPad5,
        NumPad6,
        NumPad7,
        NumPad8,
        NumPad9,
        Multiply,
        Add,
        Separator,
        Subtract,
        Decimal,
        Divide,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        NumLock = 144,
        Scroll,
        LShiftKey = 160,
        RShiftKey,
        LControlKey,
        RControlKey,
        LMenu,
        BrowserBack = 166,
        BrowserForward,
        BrowserRefresh,
        BrowserStop,
        BrowserSearch,
        BrowserFavorites,
        BrowserHome,
        VolumeMute,
        VolumeDown,
        VolumeUp,
        MediaNext,
        MediaPrevious,
        MediaStop,
        MediaPlay,
        LaunchMail,
        LaunchMediaSelect,
        LaunchApp1,
        LaunchApp2,
        Oem1 = 186,
        OemPlus,
        OemComma,
        OemMinus,
        OemPeriod,
        Oem2,
        Oem3,
        Oem4 = 219,
        Oem5,
        Oem6,
        Oem7,
        Oem8,
        Oem102 = 226,
        Process = 229,
        Packet = 231,
        Attention = 246,
        CrSel,
        ExSel,
        EraseEndOfFile,
        Play,
        Zoom,
        NoName,
        Pa1,
        OemClear,
    }
}